# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- branch_karen_guillen

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  
displayName: Testing Unit Test
  
inputs:
    
command: 'test'
    
projects: '**/xUnit.CaducaRest/*.csproj'
    
arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
    
testRunTitle: 'Unit Test'


