//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_IE.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int IdAppointment { get; set; }
        public Nullable<int> IdProfessor { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<int> IdCourse { get; set; }
        public Nullable<int> IdSchedule { get; set; }
        public Nullable<bool> StatusApprovedDisapproved { get; set; }
        public Nullable<bool> VirtualOn_Site { get; set; }
        public string ReasonForAppointment { get; set; }
        public Nullable<bool> ProfessorResponse { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
