//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_IE.Models.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IF4101_BeatySolutions_ISem_2020Entities1 : DbContext
    {
        public IF4101_BeatySolutions_ISem_2020Entities1()
            : base("name=IF4101_BeatySolutions_ISem_2020Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Canton> Canton { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<Professor> Professor { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
    
        public virtual int deleteCourse(Nullable<int> idCourse)
        {
            var idCourseParameter = idCourse.HasValue ?
                new ObjectParameter("idCourse", idCourse) :
                new ObjectParameter("idCourse", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteCourse", idCourseParameter);
        }
    
        public virtual int deleteProfessor(Nullable<int> idProfessor)
        {
            var idProfessorParameter = idProfessor.HasValue ?
                new ObjectParameter("idProfessor", idProfessor) :
                new ObjectParameter("idProfessor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteProfessor", idProfessorParameter);
        }
    
        public virtual int deleteStudent(Nullable<int> idStudent)
        {
            var idStudentParameter = idStudent.HasValue ?
                new ObjectParameter("idStudent", idStudent) :
                new ObjectParameter("idStudent", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteStudent", idStudentParameter);
        }
    
        public virtual ObjectResult<GetByIdCourse_Result> GetByIdCourse(Nullable<int> idCourse)
        {
            var idCourseParameter = idCourse.HasValue ?
                new ObjectParameter("idCourse", idCourse) :
                new ObjectParameter("idCourse", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetByIdCourse_Result>("GetByIdCourse", idCourseParameter);
        }
    
        public virtual int InsertUpdateCourse(Nullable<int> idCourse, string name, Nullable<bool> state, string semestrer, string description, string action)
        {
            var idCourseParameter = idCourse.HasValue ?
                new ObjectParameter("idCourse", idCourse) :
                new ObjectParameter("idCourse", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(bool));
    
            var semestrerParameter = semestrer != null ?
                new ObjectParameter("semestrer", semestrer) :
                new ObjectParameter("semestrer", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertUpdateCourse", idCourseParameter, nameParameter, stateParameter, semestrerParameter, descriptionParameter, actionParameter);
        }
    
        public virtual int InsertUpdateProfessor(Nullable<int> idProfessor, string degree, string action)
        {
            var idProfessorParameter = idProfessor.HasValue ?
                new ObjectParameter("idProfessor", idProfessor) :
                new ObjectParameter("idProfessor", typeof(int));
    
            var degreeParameter = degree != null ?
                new ObjectParameter("degree", degree) :
                new ObjectParameter("degree", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertUpdateProfessor", idProfessorParameter, degreeParameter, actionParameter);
        }
    
        public virtual int InsertUpdateStudent(Nullable<int> idStudent, string identificationCard, string action)
        {
            var idStudentParameter = idStudent.HasValue ?
                new ObjectParameter("idStudent", idStudent) :
                new ObjectParameter("idStudent", typeof(int));
    
            var identificationCardParameter = identificationCard != null ?
                new ObjectParameter("identificationCard", identificationCard) :
                new ObjectParameter("identificationCard", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertUpdateStudent", idStudentParameter, identificationCardParameter, actionParameter);
        }
    
        public virtual ObjectResult<SelectCourse_Result> SelectCourse()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCourse_Result>("SelectCourse");
        }
    
        public virtual int deleteCourseSP(Nullable<int> idCourse)
        {
            var idCourseParameter = idCourse.HasValue ?
                new ObjectParameter("idCourse", idCourse) :
                new ObjectParameter("idCourse", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteCourseSP", idCourseParameter);
        }
    
        public virtual int deleteProfessorSP(Nullable<int> idProfessor)
        {
            var idProfessorParameter = idProfessor.HasValue ?
                new ObjectParameter("idProfessor", idProfessor) :
                new ObjectParameter("idProfessor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteProfessorSP", idProfessorParameter);
        }
    
        public virtual int deleteStudentSP(Nullable<int> idStudent)
        {
            var idStudentParameter = idStudent.HasValue ?
                new ObjectParameter("idStudent", idStudent) :
                new ObjectParameter("idStudent", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteStudentSP", idStudentParameter);
        }
    
        public virtual int InsertUpdateCourseSP(Nullable<int> idCourse, string name, Nullable<bool> state, string semestrer, string description, string action)
        {
            var idCourseParameter = idCourse.HasValue ?
                new ObjectParameter("idCourse", idCourse) :
                new ObjectParameter("idCourse", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(bool));
    
            var semestrerParameter = semestrer != null ?
                new ObjectParameter("semestrer", semestrer) :
                new ObjectParameter("semestrer", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertUpdateCourseSP", idCourseParameter, nameParameter, stateParameter, semestrerParameter, descriptionParameter, actionParameter);
        }
    
        public virtual int InsertUpdateProfessorSP(Nullable<int> idProfessor, string degree, string action)
        {
            var idProfessorParameter = idProfessor.HasValue ?
                new ObjectParameter("idProfessor", idProfessor) :
                new ObjectParameter("idProfessor", typeof(int));
    
            var degreeParameter = degree != null ?
                new ObjectParameter("degree", degree) :
                new ObjectParameter("degree", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertUpdateProfessorSP", idProfessorParameter, degreeParameter, actionParameter);
        }
    
        public virtual int InsertUpdateStudentSP(Nullable<int> idStudent, string identificationCard, string action)
        {
            var idStudentParameter = idStudent.HasValue ?
                new ObjectParameter("idStudent", idStudent) :
                new ObjectParameter("idStudent", typeof(int));
    
            var identificationCardParameter = identificationCard != null ?
                new ObjectParameter("identificationCard", identificationCard) :
                new ObjectParameter("identificationCard", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertUpdateStudentSP", idStudentParameter, identificationCardParameter, actionParameter);
        }
    
        public virtual ObjectResult<Course> SelectCourseSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Course>("SelectCourseSP");
        }
    
        public virtual ObjectResult<Course> SelectCourseSP(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Course>("SelectCourseSP", mergeOption);
        }
    
        public virtual ObjectResult<Course> GetByIdCourseSP(Nullable<int> idCourse)
        {
            var idCourseParameter = idCourse.HasValue ?
                new ObjectParameter("idCourse", idCourse) :
                new ObjectParameter("idCourse", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Course>("GetByIdCourseSP", idCourseParameter);
        }
    
        public virtual ObjectResult<Course> GetByIdCourseSP(Nullable<int> idCourse, MergeOption mergeOption)
        {
            var idCourseParameter = idCourse.HasValue ?
                new ObjectParameter("idCourse", idCourse) :
                new ObjectParameter("idCourse", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Course>("GetByIdCourseSP", mergeOption, idCourseParameter);
        }
    }
}
