//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_IE.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation
    {
        public int IdConsultation { get; set; }
        public Nullable<int> IdCourse { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdTransmitter { get; set; }
        public Nullable<int> IdReceiver { get; set; }
    }
}
