//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_IE.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation
    {
        public int IdConsultation { get; set; }
        public Nullable<int> IdCourse { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdTransmitter { get; set; }
        public Nullable<int> IdReceiver { get; set; }
    }
}
