//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_IE.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int idCourse { get; set; }
        public string name { get; set; }
        public bool state { get; set; }
        public string semestrer { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public Nullable<int> createBy { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
