//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_IE.Models.Data
{
    using System;
    
    public partial class SelectCourse_Result1
    {
        public int IdCourse { get; set; }
        public string Name { get; set; }
        public string Semestrer { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<bool> state { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
