//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_IE.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int idUserProfile { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string userPhoto { get; set; }
        public string interests { get; set; }
        public string email { get; set; }
        public bool isAdmin { get; set; }
        public bool isEnable { get; set; }
        public int idCanton { get; set; }
        public int idProvince { get; set; }
        public int idDistrict { get; set; }
        public Nullable<int> createBy { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    }
}
