name: SPA_IE_TEST

on: 
  push:
     branches: 
        - master
  pull_request:
      branches:
        - master

jobs: 
  build-project:
     runs-on: ubuntu-latest
     steps:
       - name: Setup Checkout Action 
         uses: actions/checkout@v2
       - name: Set up .NET
         uses: actions/setup-dotnet@v1
         with: 
           dotnet-version: 3.1.100
       - name: Build project
         run: dotnet build
         working-directory: ./SPA_IE